name: euclid-ml
channels:
  - pytorch
  - nvidia              # needed for pytorch-cuda
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.5.*
  - torchvision=0.20.*
  - torchaudio=2.5.*
  - pytorch-cuda=12.1   # pulls the right CUDA runtime/toolkit
  - numpy=1.26.*
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - pillow
  - pyarrow
  - pip
  - pip:
      - absl-py==2.1.0
      - accelerate==1.1.1
      - albucore==0.0.24
      - albumentations==2.0.8
      - datasets==4.0.0
      - einops==0.8.0
      - fsspec==2025.3.0
      - gudhi==3.7.1
      - huggingface-hub==0.34.4
      - lightning==2.4.0
      - pytorch-lightning==2.4.0
      - nflows==0.14
      - numba==0.60.0
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - protobuf==4.25.5
      - safetensors==0.4.5
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - timm==1.0.19
      - tiktoken==0.3.0
      - tokenizers==0.15.2
      - torchinterp1d==1.1
      - torchmetrics==1.6.0
      - tqdm==4.66.3
      - transformers==4.38.0
      - umap-learn==0.5.3
      - wandb==0.21.1
